import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MessageSquare, Loader2, Clock, TrendingUp } from "lucide-react";
import { QueryResponse } from "@/pages/Index";

interface ResponseSectionProps {
  response: QueryResponse | null;
  isLoading: boolean;
}

export const ResponseSection = ({ response, isLoading }: ResponseSectionProps) => {
  if (isLoading) {
    return (
      <Card className="h-fit">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <MessageSquare className="w-5 h-5 text-agri-earth" />
            AI Response
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col items-center justify-center py-12 space-y-4">
            <Loader2 className="w-12 h-12 animate-spin text-agri-green" />
            <p className="text-muted-foreground">Processing your query...</p>
            <p className="text-sm text-muted-foreground">
              Retrieving relevant documents and generating response
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!response) {
    return (
      <Card className="h-fit">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <MessageSquare className="w-5 h-5 text-agri-earth" />
            AI Response
          </CardTitle>
          <CardDescription>Your response will appear here</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col items-center justify-center py-12 space-y-2">
            <MessageSquare className="w-16 h-16 text-muted-foreground/30" />
            <p className="text-muted-foreground text-center">
              Submit a query to get AI-powered agriculture advice
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="h-fit">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <MessageSquare className="w-5 h-5 text-agri-earth" />
          AI Response
        </CardTitle>
        <CardDescription>Generated by {response.agent}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Query Info */}
        <div className="p-3 bg-muted/50 rounded-lg space-y-2">
          <p className="font-semibold text-sm text-foreground">Query:</p>
          <p className="text-sm text-muted-foreground">{response.query}</p>
          <div className="flex flex-wrap gap-2 mt-2">
            {response.crop && <Badge variant="secondary">{response.crop}</Badge>}
            {response.season && <Badge variant="secondary">{response.season}</Badge>}
            {response.region && <Badge variant="secondary">{response.region}</Badge>}
            <Badge variant="outline" className="gap-1">
              <TrendingUp className="w-3 h-3" />
              {Math.round(response.confidence * 100)}% confidence
            </Badge>
            <Badge variant="outline" className="gap-1">
              <Clock className="w-3 h-3" />
              {response.processingTime}ms
            </Badge>
          </div>
        </div>

        {/* Response */}
        <div className="space-y-2">
          <p className="font-semibold text-sm text-foreground">Response:</p>
          <div className="prose prose-sm max-w-none">
            <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">
              {response.response}
            </p>
          </div>
        </div>

        {/* Metadata */}
        <div className="pt-4 border-t border-border">
          <div className="grid grid-cols-2 gap-4 text-xs text-muted-foreground">
            <div>
              <span className="font-semibold">Agent Type:</span>
              <p className="mt-1">{response.agent}</p>
            </div>
            <div>
              <span className="font-semibold">Processing Time:</span>
              <p className="mt-1">{response.processingTime}ms</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
